apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ""
  namespace: ""
  labels: {}
  annotations: {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ""
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ""
