apiVersion: v1
kind: Service
metadata:
  name: ""
  namespace: ""
  labels: {}
  annotations: {}
spec:
  selector: {}
  type: ClusterIP
  clusterIP: ""
  ports:
    - port: 0
      targetPort: 0
      nodePort: 0
