apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: ""
  namespace: ""
  labels: {}
  annotations: {}
spec:
  entrypoint: ""
  templates:
    - name: ""
      container:
        image: ""
