[package]
name = "reqwest"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = [
    "blocking",
    "json",
    "cookies",
    "gzip",
    "rustls-tls",
], default-features = false }
serde = { version = "1.0", features = ["derive"] }
bytes = "1"
